on: 
  push:
    branches:
      - master

jobs:
  build_pelican_blog:
    runs-on: ubuntu-latest
    name: Publish html
    steps:
      - name: Github Actions for x-wei's pelican blog
        uses: X-Wei/pelican-gh-actions-xwei@v0.0.1