name: auto-publish-html

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'pelican_dir/content/**'

jobs:
  build_pelican_blog:
    runs-on: ubuntu-latest
    name: Publish html
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Generate pelican html files and commit
        uses: X-Wei/pelican-gh-actions-xwei@v0.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GH_TOKEN }}
          GH_PAGES_BRANCH: master