on: 
  push:
    branches:
      - master

jobs:
  build_pelican_blog:
    runs-on: ubuntu-latest
    name: Publish html
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Github Actions for x-wei's pelican blog
        uses: X-Wei/pelican-gh-actions-xwei@v0.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GH_TOKEN }}
          GH_PAGES_BRANCH: master